[phases.setup]
nixPkgs = ["nodejs_20", "bun", "pnpm", "python3", "gcc", "gnumake"]

[phases.install]
cmds = ["pnpm i --frozen-lockfile"]

[phases.build]
cmds = ["rm -f bun.lockb && bun install && turbo run build && bun build.ts"]

[start]
cmd = "bun run start-server.ts"
